---
title: "Regulatory Reporting Calendar: AY 2022-23"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1600px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE)
```

```{r prepEnv}

library(dplyr)
library(ggplot2)
library(readxl)
library(lubridate)

setwd('C:\\Users\\Thomas Sharpe\\Desktop\\AIHEC_IR24\\AccelerateR\\Planning')

```

```{r getData}

rawData <- read_excel('calendarData2022_23.xlsx', sheet = 'annual')
reportData <- 
	rawData %>%
	arrange(DueDate)


reportData$DueDate <- as.Date(reportData$DueDate)

```

```{r plot, fig.width=18, fig.height=10}

curDay <- as.Date('2023-05-03') #Sys.Date()
curMonth <- month(curDay)

reportCount <- length(reportData$Report)
dayPosition <- ifelse(between(curMonth,7,9),reportCount - 20,reportCount - .5)

ggplot(data = reportData,
	   aes(x = reorder(Report,desc(DueDate)), y= DueDate, colour = Completed, shape = Completed)) + 
	geom_point(size = 10) +
	scale_shape_manual(values = c("\u2713","\u4", "\u25A0"), breaks = c('Completed','Not Completed','Future')) +
	scale_color_manual(values = c('seagreen4','tomato4','slateblue4'), breaks = c('Completed','Not Completed','Future')) +
	scale_y_date(date_breaks = "1 week", date_labels = "%b %d") +
	geom_text(aes(label = format(DueDate, "%b %d")), hjust = -.3) +
	coord_flip() +
	geom_hline(yintercept = curDay,color = 'black',size = 1, linetype = 'dotted') +
	annotate("text", x = dayPosition, y = curDay + days(2), label = paste('Today (',format(curDay, "%b %d"),')',sep = ''), fontface = 8) +
	labs(x ='', y = '', title = 'Regulatory Reporting Calendar: AY 2022-23') +
	theme_bw() +
	theme(plot.title = element_text(hjust = .5),
		  axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank(),
		  axis.ticks.y = element_blank(), axis.text.y = element_text(size = 10),
		  panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.major.y = element_line(size = .1, color = 'seashell3'),
		  panel.border = element_blank(), panel.background = element_rect(fill = 'gray98', colour = 'gray98'),
		  legend.position = c(.8,.9), legend.title = element_blank(), legend.background = element_rect(fill = 'gray98', colour = 'gray98'), legend.text = element_text(size = 12))


```


